"""lab_utils — shared utilities for the Research Lab.

Contains only reusable code: metrics, integrators, orbital canon, and result I/O.
Each module is self-contained and covered by tests in `src/lab_utils/tests/`.
"""

from lab_utils.earth_frames import (
    DEG,
    JD_J2000,
    AU_KM,
    DUT1_FROZEN_S,
    R_SUN_KM,
    T_SIDEREAL_S,
    TT_MINUS_UTC_S,
    ecef_to_latlon,
    eci_to_ecef,
    gmst_rad_iau1982,
    lst_at_node_hours,
    node_lon_from_raan_gmst,
    spherical_trig_latlon,
    subsolar_dec_rad,
    subsolar_lon_rad,
    sun_unit_and_dist_km,
    wrap_longitude_deg,
)
from lab_utils.integrators import rk4_propagate, rk4_step
from lab_utils.metrics import (
    convergence_rate,
    l2_norm_error,
    max_abs_error,
    relative_l2_error,
)
from lab_utils.orbits import (
    ECC_GUARD_ABS,
    J2_EARTH,
    MU_EARTH_KM3S2,
    NODE_GUARD_REL,
    OMEGA_EARTH_RAD_S,
    R_EARTH_KM,
    SSO_TARGET_DEG_DAY,
    coe_to_rv_eci,
    j2_rhs,
    mean_motion,
    orbital_period,
    rotation_matrix_313,
    rv_to_coe_eci,
    seed_state,
    solve_kepler,
    sso_existence_max_sma,
    sso_inclination_rad,
    steps_per_orbit,
    true_anomaly_from_E,
)
from lab_utils.results import save_json_result

__all__ = [
    "AU_KM",
    "DEG",
    "DUT1_FROZEN_S",
    "ECC_GUARD_ABS",
    "JD_J2000",
    "J2_EARTH",
    "MU_EARTH_KM3S2",
    "NODE_GUARD_REL",
    "OMEGA_EARTH_RAD_S",
    "R_EARTH_KM",
    "R_SUN_KM",
    "SSO_TARGET_DEG_DAY",
    "T_SIDEREAL_S",
    "TT_MINUS_UTC_S",
    "convergence_rate",
    "ecef_to_latlon",
    "eci_to_ecef",
    "gmst_rad_iau1982",
    "j2_rhs",
    "l2_norm_error",
    "lst_at_node_hours",
    "max_abs_error",
    "mean_motion",
    "node_lon_from_raan_gmst",
    "orbital_period",
    "relative_l2_error",
    "rk4_propagate",
    "rk4_step",
    "rotation_matrix_313",
    "rv_to_coe_eci",
    "save_json_result",
    "seed_state",
    "solve_kepler",
    "spherical_trig_latlon",
    "sso_existence_max_sma",
    "sso_inclination_rad",
    "steps_per_orbit",
    "subsolar_dec_rad",
    "subsolar_lon_rad",
    "sun_unit_and_dist_km",
    "true_anomaly_from_E",
    "wrap_longitude_deg",
]
